[package]
name = "robius-authentication"
version = "0.1.0"
edition = "2021"

[lib]
# name = "auth"
 crate-type = ["dylib"]

#[target.'cfg(target_os = "android")'.lib]
#crate-type = ["dylib"]

[dependencies]
cfg-if = "1.0.0"
log = "0.4.20"

[target.'cfg(target_os = "android")'.dependencies.android_logger]
android_logger = "0.13"

[target.'cfg(target_os = "android")'.dependencies.jni]
version = "0.21.1"


[target.'cfg(target_os = "android")'.dependencies.jni-sys]
version = "0.4.0"
default-features = false

[target.'cfg(target_vendor = "apple")'.dependencies.block2]
version = "0.4.0"

[target.'cfg(target_vendor = "apple")'.dependencies.tokio]
version = "1.35.1"
default-features = false
features = ["sync"]

[target.'cfg(target_vendor = "apple")'.dependencies.icrate]
version = "0.1.0"
features = [
    "Foundation_NSError",
    "Foundation_NSString",
    "LocalAuthentication",
    "LocalAuthentication_LAContext"
]

[target.'cfg(target_os = "linux")'.dependencies.pam-client]
version = "0.5.0"

[target.'cfg(target_os = "linux")'.dependencies.pam]
version = "0.8.0"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.52.0"
features = [
    "Foundation",
    "Security_Credentials_UI",
]

