[package]
name = "robius-authentication"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1.0.0"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.52.0"
features = [
    "Foundation",
    "Security_Credentials_UI",
]

[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies.block2]
version = "0.4.0"

[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies.tokio]
version = "1.35.1"
default-features = false
features = ["sync"]

[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies.icrate]
verision = "0.1.0"
features = [
    "Foundation_NSError",
    "Foundation_NSString",
    "LocalAuthentication",
    "LocalAuthentication_LAContext"
]

